### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by thorbjorn444** [nerdyrodent/VQGAN-CLIP#1]
Hey! Would you mind adding a requirements.txt? I'm really just looking for the version #s of the relevant repos that are used here. It should be straightforward to extract from the output of "pip freeze". Thanks in advance!

**Comment by nerdyrodent** [comment]
Hi, I've added a requirements.txt (from pip freeze > requirements.txt) and vqgan.yml (from conda env export --name vqgan > vqgan.yml). Hopefully that should do the job?

**Comment by thorbjorn444** [comment]
Thank you!
