### ISSUE TITLE
Invalid start byte

### ISSUE THREAD

**Issue by JCreedah** [nerdyrodent/VQGAN-CLIP#108]
Hi,

Please help, it seems there is an issue with utf-8 codec. Please see attached image.
![image](https://user-images.githubusercontent.com/97258105/148475337-aa3c19c7-d4e2-4730-8f11-f3139534b8b7.png)

**Comment by nerdyrodent** [comment]
You are trying to use an invalid config or checkpoint file. Try downloading the files again.

**Comment by JCreedah** [comment]
I've tried downloading stuff again, and from other sources too.
Could the config be incorrect because I have things split across 2 drives?
