### ISSUE TITLE
Richer demo images 

### ISSUE THREAD

**Issue by johndpope** [nerdyrodent/VQGAN-CLIP#11]
https://twitter.com/e08477/status/1418440857578098691?s=21

Would love to be able to recreate this. We need to build out a taxonomy of styles. 

I. Mentioned on a comment on. YouTube that could take a video / ffmpeg and stick each image in and see it reimagine video.  Can you try with the something? And post result?

**Comment by nerdyrodent** [comment]
`opt_tester.sh` creates collages like this - https://twitter.com/NerdyRodent/status/1415358009614680067?s=20
 Even though I was using it to show learning rate changes, it could be changed to do something similar to the twitter post you linked?

For video `video_styler.sh` that is one attempt to style a video, if that's any good? Not the smoothest in the world though, unfortunately - https://twitter.com/NerdyRodent/status/1414624016808226819?s=20

**Comment by johndpope** [comment]
Great thanks. Keep up the great work.

**Comment by johndpope** [comment]
I think just need get the names down to augment your script. You could almost throw a dictionary at this thing it seems to get a varied image based off the mushroom example.
