### ISSUE TITLE
Link to download VQGAN 1024 yaml and checkpoints not working

### ISSUE THREAD

**Issue by Hritikbansal** [nerdyrodent/VQGAN-CLIP#114]
You might want to update the download instructions to:

`curl -L -o vqgan_imagenet_f16_1024.ckpt -C - 'https://heibox.uni-heidelberg.de/d/8088892a516d4e3baf92/files/?p=%2Fckpts%2Flast.ckpt&dl=1' `

and 

`curl -L -o vqgan_imagenet_f16_1024.yaml -C - 'https://heibox.uni-heidelberg.de/d/8088892a516d4e3baf92/files/?p=%2Fconfigs%2Fmodel.yaml'`

**Comment by nerdyrodent** [comment]
The example manual download is for ``vqgan_imagenet_f16_16384.yaml``, rather than ``vqgan_imagenet_f16_1024.ckpt``. The download script has the exact same ``vqgan_imagenet_f16_1024.ckpt`` link as provided?

**Comment by Hritikbansal** [comment]
My bad, I did not look in the download script. The colab notebook has incorrect links then:

`if imagenet_1024:`
 `!curl -L -o vqgan_imagenet_f16_1024.yaml -C - 'http://mirror.io.community/blob/vqgan/vqgan_imagenet_f16_1024.yaml' #ImageNet 1024`

` !curl -L -o vqgan_imagenet_f16_1024.ckpt -C - 'http://mirror.io.community/blob/vqgan/vqgan_imagenet_f16_1024.ckpt'  #ImageNet 1024`

Might want to correct those.
