### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement torch==1.9.0+cu111 (from versions: none)

### ISSUE THREAD

**Issue by dustovshio** [nerdyrodent/VQGAN-CLIP#115]
>py -m pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.9.0+cu111 (from versions: none)
ERROR: No matching distribution found for torch==1.9.0+cu111

**Comment by nerdyrodent** [comment]
Ensure you have your Nvidia drivers & Nvidia CUDA toolkit installed.
For more information on installing PyTorch, see https://pytorch.org/get-started/locally/#linux-installation
