### ISSUE TITLE
ModuleNotFoundError: No module named ...

### ISSUE THREAD

**Issue by Zupanico** [nerdyrodent/VQGAN-CLIP#116]
Hi,
I followed your tutorial on youtube, worked great the first time without any problems.
I closed the Anaconda prompt, and after this nothing worked and I got multiple messages like this :
`(vqgan) C:\vqgan\VQGAN-CLIP>python generate.py -p "sunset over the valley" -s 256 256 -cuts 1
Traceback (most recent call last):
  File "C:\vqgan\VQGAN-CLIP\generate.py", line 30, in <module>
    from torch_optimizer import DiffGrad, AdamP
ModuleNotFoundError: No module named 'torch_optimizer'`

Sometimes I got the module not found omega conf, etc.

What's the process to make it unusable ?

Thanks in advance

Specs : 
Windows 10
i7-8750H
Quadro P1000 4GB
RAM 48 GB

**Comment by nerdyrodent** [comment]
from the readme:
```pip install ftfy regex tqdm omegaconf pytorch-lightning IPython kornia imageio imageio-ffmpeg einops torch_optimizer```
