### ISSUE TITLE
Download nvidia-smi -L SyntaxError:invalid syntax

### ISSUE THREAD

**Issue by charlesf218** [nerdyrodent/VQGAN-CLIP#127]
Trying to open the program, renamed to python images to make it a little easier. Heres what I entered into cmd:

cd desktop

python pythonimages.py

nvidia-smi -L 
  ^
SyntaxError:invalid syntax

Please help, thanks

**Comment by tavisc** [comment]
You installed this or you're in the process of installing it? 

I ask because I don't see pythonimages.py or nividia-smi -L anywhere in the documentation.

**Comment by charlesf218** [comment]
I am trying to download it

**Comment by tavisc** [comment]
You need Anaconda, then use :
`conda create --name vqgan python=3.9
conda activate vqgan`

**Comment by charlesf218** [comment]
So I did that...

All I get is the command prompt, how can I launch the actual interactive interface? Also thank you so much for the help

**Comment by tavisc** [comment]
There isn't a gui, Have you read through the entire guide? It spells out exactly how to use this...

**Comment by charlesf218** [comment]
oh lol sorry

**Comment by charlesf218** [comment]
is there somthing that has gui? or are my only options to use all these commands?
