### ISSUE TITLE
module error

### ISSUE THREAD

**Issue by deboi238** [nerdyrodent/VQGAN-CLIP#128]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-9-8f93516a9283>](https://localhost:8080/#) in <module>()
     11 from omegaconf import OmegaConf
     12 from PIL import Image
---> 13 from taming.models import cond_transformer, vqgan
     14 import taming.modules
     15 import torch

ModuleNotFoundError: No module named 'taming'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

pls help

**Comment by nerdyrodent** [comment]
Be sure to install the requirements.

**Comment by deboi238** [comment]
I was using google calob
