### ISSUE TITLE
General Questions 

### ISSUE THREAD

**Issue by pouyiouk** [nerdyrodent/VQGAN-CLIP#136]
I would like to ask the following questions out of curiosity - for information since I am new to this field.

- What is the best optimising agent to use - currently the default one is "Adam" -  benefits of each if its possible to explain them to me please.
- Can I download and use all pre-trained models simultaneously or is it just one at a time?

**Comment by nerdyrodent** [comment]
* See https://pytorch.org/docs/stable/optim.html and https://github.com/jettify/pytorch-optimizer for some optimiser information. Adam is a reasonable general purpose option.
* Yes, simply set everything to true in [download_models.sh](https://github.com/nerdyrodent/VQGAN-CLIP/blob/main/download_models.sh)
