### ISSUE TITLE
Error message about conda activate

### ISSUE THREAD

**Issue by bitcoinmeetups** [nerdyrodent/VQGAN-CLIP#14]
Error message about conda activate:

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.                                              To initialize your shell, run                                                                                                               $ conda init <SHELL_NAME>                                                                                                           Currently supported shells are:                                       - bash

But if I try to run conda init I get this:

a init                  no change     /root/anaconda3/condabin/conda                        no change     /root/anaconda3/bin/conda                             no change     /root/anaconda3/bin/conda-env                         no change     /root/anaconda3/bin/activate                          no change     /root/anaconda3/bin/deactivate                        no change     /root/anaconda3/etc/profile.d/conda.sh                no change     /root/anaconda3/etc/fish/conf.d/conda.fish            no change     /root/anaconda3/shell/condabin/Conda.psm1             no change     /root/anaconda3/shell/condabin/conda-hook.ps1         no change     /root/anaconda3/lib/python3.8/site-packages/xontrib/conda.xsh                                                             no change     /root/anaconda3/etc/profile.d/conda.csh               no change     /root/.bashrc                                         No action taken.

And activate vqgan will still not work.

**Comment by bitcoinmeetups** [comment]
So then I also get 

~/anaconda3# python generate.py                              python: can't open file 'generate.py': [Errno 2] No such file or directory

**Comment by bitcoinmeetups** [comment]
I mean I run conda init bash not conda init

**Comment by nerdyrodent** [comment]
Hi. I'm afraid I've never seen Anaconda do that. It's only ever been a simple download and install. I'd try installing again, but when the installer prompts “Do you wish the installer to initialize Anaconda3 by running conda init?”, say yes instead of no.

https://docs.anaconda.com/anaconda/install/linux/
