### ISSUE TITLE
Unable to run from bash scripts

### ISSUE THREAD

**Issue by BitastaB** [nerdyrodent/VQGAN-CLIP#140]
Hi. I want to run it from a bash script but it is not accepting string input in prompts with spaces. 

I used : `python generate.py -p "Flower girl"`

and getting the following error 
![image_2022_03_01T16_21_22_355Z](https://user-images.githubusercontent.com/12182964/157045646-cbb6f934-128e-4b9e-a59f-e9f4da6b611b.png)
:

My bash script looks like this : 

```
#!/bin/bash

srun $(head -n $SLURM_ARRAY_TASK_ID commands.txt | tail -n 1)

exit 0
```

Would be glad for any help if possible.

**Comment by nerdyrodent** [comment]
See [opt_tester.sh](https://github.com/nerdyrodent/VQGAN-CLIP/blob/main/opt_tester.sh) and the various other bash scripts for examples of running.
