### ISSUE TITLE
RuntimeError: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnCreate(handle)`

### ISSUE THREAD

**Issue by Lileisd** [nerdyrodent/VQGAN-CLIP#143]
Traceback (most recent call last):
  
RuntimeError: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnCreate(handle)`

Process finished with exit code 1

**Comment by nerdyrodent** [comment]
See https://github.com/nerdyrodent/VQGAN-CLIP#troubleshooting
