### ISSUE TITLE
Do we need to train VQGAN and CLIP together?

### ISSUE THREAD

**Issue by charlotte12l** [nerdyrodent/VQGAN-CLIP#146]
In training, do we need to train VQGAN and CLIP together? Or they are just trained separately but when inference we will use them two.

**Comment by nerdyrodent** [comment]
They're pre-trained.

**Comment by charlotte12l** [comment]
@nerdyrodent Actually I mean when I finetune(train) the model, do I just train VQGAN and CLIP separately, or train them together? I guess just separately is enough?
