### ISSUE TITLE
zoom.sh and random.sh file issue 

### ISSUE THREAD

**Issue by ayush9198gupta** [nerdyrodent/VQGAN-CLIP#148]
Hi @nerdyrodent 

I am working on your code it works fine on single line text with generate.py but how we can modify the code for multiple text in single file and code will generate images one by one according to text in the file.

I have also run both .sh files but they were not working , kindly help or modify the sh file accordingly.

find the screen shot for reference.

![Screenshot from 2022-04-26 17-42-44](https://user-images.githubusercontent.com/61581309/165298092-266563f2-201a-4ad2-a7ba-bf1800fc38c2.png)

**Comment by nerdyrodent** [comment]
You've forgotten to install ImageMagick
