### ISSUE TITLE
No such file or directory: '..checkpoints\\vqgan_imagenet_f16_16384.yaml'

### ISSUE THREAD

**Issue by xJAS3x** [nerdyrodent/VQGAN-CLIP#15]
I'm not quite sure what's going on here but I do have the file in the correct subfolder. I reinstalled the dependencies and still get the same error. This is on a Windows 10 build.

![image](https://user-images.githubusercontent.com/16025417/127417480-5bc7b067-ab30-424d-9ac4-08e57579a69c.png)
![image](https://user-images.githubusercontent.com/16025417/127417760-a18a6544-8841-44f2-a096-186e4084fb3d.png)

**Comment by zhanghongyong123456** [comment]
> I'm not quite sure what's going on here but I do have the file in the correct subfolder. I reinstalled the dependencies and still get the same error. This is on a Windows 10 build.
> 
> ![image](https://user-images.githubusercontent.com/16025417/127417480-5bc7b067-ab30-424d-9ac4-08e57579a69c.png)
> ![image](https://user-images.githubusercontent.com/16025417/127417760-a18a6544-8841-44f2-a096-186e4084fb3d.png)
You can manually download these files according to the url and change the name to match it，like me
![image](https://user-images.githubusercontent.com/48466610/127446131-0db96e9a-95d4-4ad0-8433-b62561302e08.png)
