### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by ammartist** [nerdyrodent/VQGAN-CLIP#150]
I am getting this error:
RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 11.00 GiB total capacity; 10.11 GiB already allocated; 0 bytes free; 10.16 GiB reserved in total by PyTorch)

When I try to run this:
python generate.py -p "The inside of a sphere" -zvid -i 4500 -zse 20 -vl 10 -zsc 0.97 -opt Adagrad -lr 0.15 -se 4500

How can I Fix this? change and make it work? I am running on 2080 Ti 11 GB VRAM

**Comment by nerdyrodent** [comment]
See https://github.com/nerdyrodent/VQGAN-CLIP#runtimeerror-cuda-out-of-memory
