### ISSUE TITLE
**completely unusable colab!!!** ModuleNotFoundError: No module named 'torch._six'

### ISSUE THREAD

**Issue by benku101** [nerdyrodent/VQGAN-CLIP#165]
"---> 11 from torch._six import string_classes"
This stops the entire process. Unable to run the script further. I tried this on several other colabs and they yield a similar error.
I have been doing this for years, i'm doing everything right. Please fix this!!!

**Comment by nerdyrodent** [comment]
This repo contains no notebooks and is for running locally

**Comment by loboere** [comment]
There is a colab in the readme of this repository, but it gives an error, does that mean that we will never be able to run this in colab again?
Is there another way or functional website that runs this?
