### ISSUE TITLE
about  run time ？ It takes less than a minute

### ISSUE THREAD

**Issue by zhanghongyong123456** [nerdyrodent/VQGAN-CLIP#18]
I found a magical realization that took less than a minute
https://huggingface.co/spaces/akhaliq/VQGAN_CLIP
![image](https://user-images.githubusercontent.com/48466610/128172329-7bb26fa5-e02a-4212-b017-087ff609437a.png)

**Comment by nerdyrodent** [comment]
Nice!

**Comment by mjc619** [comment]
god how the times have changed 
![image](https://user-images.githubusercontent.com/8377727/136016991-c3154511-37e0-45f3-b6bd-9245b60ca2cb.png)
