### ISSUE TITLE
Tensor is not a torch image

### ISSUE THREAD

**Issue by tnoya001** [nerdyrodent/VQGAN-CLIP#20]
Hi. Thanks for the repo. I was just trying to test it, but I keep running into this:

 traceback (most recent call last): file "/home/paperspace/vqgan-clip/generate.py", line 552, in <module> train(i) file "/home/paperspace/vqgan-clip/generate.py", line 535, in train lossall = ascend_txt() file "/home/paperspace/vqgan-clip/generate.py", line 514, in ascend_txt iii = perceptor.encode_image(normalize(make_cutouts(out))).float() file "/home/paperspace/anaconda3/envs/vqgan/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 163, in __call__ return f.normalize(tensor, self.mean, self.std, self.inplace) file "/home/paperspace/anaconda3/envs/vqgan/lib/python3.9/site-packages/torchvision/transforms/functional.py", line 201, in normalize raise typeerror('tensor is not a torch image.') typeerror: tensor is not a torch image.

Any idea how to fix it? Really appreciate any help.

**Comment by nerdyrodent** [comment]
Not seen that one before! What options are you using when you run the script?

**Comment by tnoya001** [comment]
It happened with the basic: python generate.py -p "A painting of an apple in a fruit bowl"

But I think I've narrowed it down to either my Paperspace GPU (V100) or CUDA Toolkit version, as I also ran the script from a LambdaLabs server and it worked straight out of the box (2x.a6000)
