### ISSUE TITLE
Can't go past iteration 1500

### ISSUE THREAD

**Issue by ryudrigo** [nerdyrodent/VQGAN-CLIP#25]
Temporary solution is to pass in a 'cpe' argument that is any value greater the 'i' argument. As in:

python generate.py  -i 2000 -p "vase" -cpe 3000

Error message points to generate.py line 620
Code is trying to go to the next story step when prompt is a single sentence.

**Comment by nerdyrodent** [comment]
Thanks! Now defaults to 0.
