### ISSUE TITLE
about  args.augment ，What are parameters for

### ISSUE THREAD

**Issue by zhanghongyong123456** [nerdyrodent/VQGAN-CLIP#28]
I pulled the new code and found that many new parameters appeared. I would like to know the functions of these parameters. I am looking forward to your reply

This error occurred when I adjusted the code to make it easier for the output path to be not output.png, but I could not solve it. This error also occurred when I downloaded a new source code, I do not know where I got it wrong
![image](https://user-images.githubusercontent.com/48466610/130187814-2176d1b0-edbe-4813-a604-e90dd400547a.png)

**Comment by nerdyrodent** [comment]
The augments option allows you to pick your own list of augments, rather than the default.
More information on augments is available at https://kornia.readthedocs.io/en/latest/augmentation.module.html

**Comment by zhanghongyong123456** [comment]
> The augments option allows you to pick your own list of augments, rather than the default.
> More information on augments is available at https://kornia.readthedocs.io/en/latest/augmentation.module.html
k, I'll check it out. Thank you very much for your reply
