### ISSUE TITLE
Why do I get different ouputs when using the same input on a different repo?

### ISSUE THREAD

**Issue by shaolinseed** [nerdyrodent/VQGAN-CLIP#29]
I got an amazing output that i got on the google collab notebook and am trying to replicate it to a larger scale running locally on my 3090. For some reason the outputs appear to have a different style than that of collab (im using the same model, prompt, seed and save interval..) 

Is there something thats been altered ? Is it to do with the optimizer or learning rate? (these can't be specified on the collab notebook).

Thanks alot for this bit of software it has given me hours of experimenting and fun!

**Comment by nerdyrodent** [comment]
The defaults are the same as the notebook, so the outputs should be fairly similar, though randomness will still be a factor. There is a "-d" option with this one to make things a bit more deterministic, but there is still randomness.

**Comment by shaolinseed** [comment]
> The defaults are the same as the notebook, so the outputs should be fairly similar, though randomness will still be a factor. There is a "-d" option with this one to make things a bit more deterministic, but there is still randomness.

hmm, theres definately somehting different going on. I've tried multiple images and it appears your version has a different style to the outputs i'm getting using sborquez docker version and the collab notebook. I will post some examples later today to show you what i mean - it's almost like a more blocky style,  hard to explain.

**Comment by shaolinseed** [comment]
![nerdy_alien](https://user-images.githubusercontent.com/58080758/131213470-3b908cdc-83e6-4f01-ba70-7126a0a3e3e3.png)
![standard_alien](https://user-images.githubusercontent.com/58080758/131213472-b6d0ce90-17b8-4849-bffc-1f9c0d619921.png)

**Comment by shaolinseed** [comment]
this is what i mean each time i get a certain style when using your repo , been trying to figure out why but not sure..

**Comment by nerdyrodent** [comment]
Mine is based of the linked notebook, so if you're not using that that same linked notebook then that will account for the differences.

**Comment by nerdyrodent** [comment]
I've now added the "--cut_method" option which allows for older cutout methods to be used, such an in the pre-kornia and pooling days. Note that the aug option only works with the latest cut method.

**Comment by rlallen-nps** [comment]
Different resolutions will produce different output. I don't know of a way to produce the same image when using a different resolution. 

Additionally, I've seen some notebooks use a learning rate optimizer, like StepLR, which can be overlooked since it's not in the normal parameters but definitely has an effect on the output.

**Comment by nerdyrodent** [comment]
> Different resolutions will produce different output. I don't know of a way to produce the same image when using a different resolution.

That is expected behaviour. Even the same size won't generate the same image each time.
