### ISSUE TITLE
Saving each iteration to create a video

### ISSUE THREAD

**Issue by shaolinseed** [nerdyrodent/VQGAN-CLIP#3]
Is there a way I can save each image along the process rather than just the final output? Then using ffmpeg to combine the images into an animation? I've got it working on my PC! just interested in that feature as I can't get 900*900 on collab.. Thanks!

**Comment by nerdyrodent** [comment]
There is indeed. Make a directory called "steps" and uncomment what is currently line 395:
`#imageio.imwrite('./steps/' + str(i) + '.jpg', np.array(img))`

**Comment by nerdyrodent** [comment]
The current version now has the `-vid` option. E.g.
```python generate.py -p "A steps video" -vid True```

**Comment by shaolinseed** [comment]
> The current version now has the `-vid` option. E.g.
> `python generate.py -p "A steps video" -vid True`

great thanks alot man !
