### ISSUE TITLE
Pretrained model download links not working

### ISSUE THREAD

**Issue by microraptor** [nerdyrodent/VQGAN-CLIP#33]
The pretrained model download links in the download script and readme is unreachable for me: [http://mirror.io.community](http://mirror.io.community)

However, the links on the taming-transformers repo can be used for downloading the models:
[https://github.com/CompVis/taming-transformers#overview-of-pretrained-models](https://github.com/CompVis/taming-transformers#overview-of-pretrained-models)
The .yaml and .ckpt then have to be renamed accordingly.

If this is a common issue, the readme and download script should be updated.

**Comment by nerdyrodent** [comment]
Thanks, I've removed the mirrors.
