### ISSUE TITLE
Models mirrors have been removed

### ISSUE THREAD

**Issue by ouhenio** [nerdyrodent/VQGAN-CLIP#37]
First of all, thank you so much for this notebook. It's my favorite version of the VQGAN + CLIP notebooks out there 😊. 

As noted by @nerdyrodent in a previous issue, since a couple of days ago, no matter what model you choose to download you'll get the message  `Could not resolve host: mirror.io.community`.

**Comment by CarlosLannister** [comment]
@ouhenio you can use the Notebooks from the main repository https://github.com/justinjohn0306/VQGAN-CLIP

**Comment by ouhenio** [comment]
It works. Thanks @CarlosLannister!
