### ISSUE TITLE
No module named 'CLIP'

### ISSUE THREAD

**Issue by Lucaslpena** [nerdyrodent/VQGAN-CLIP#4]
After following your video—with the conda approach, making the environment, updating it with the `.yml` and getting torch==1.9.0—I am getting the following error from `generate.py`:

ModuleNotFoundError: No module named 'CLIP'

I tried to even install the CLIP repo via pip before re-installing torch and everything else but it didn't work...

I am sure this is a silly issue

**Comment by nerdyrodent** [comment]
In my environment both CLIP and taming-transformers are present in the local directory, and so aren't in the requirements.txt or vqgan.yml. You can get them by using git clone:
```
git clone https://github.com/openai/CLIP
git clone https://github.com/CompVis/taming-transformers.git
```

**Comment by Lucaslpena** [comment]
Thanks for the fast response, git cloned the repos but how do I install their respective modules to utilize them for the `import` statements in `generate.py`? In other words even with the repos cloned locally I get the same error because having the local repos in the file system does not install them in via pip

**Comment by Lucaslpena** [comment]
Got it, thank you!!!
