### ISSUE TITLE
Problem unidentified by a newbie (me)

### ISSUE THREAD

**Issue by glouglou2marseille** [nerdyrodent/VQGAN-CLIP#42]
Hello, I followed your video (thank a lot by the way, it seems like I did not followed well actually) 
Maybe you'll understand what I can do at this point : 

(vqgan) C:\Users\Milaj\github\VQGAN-CLIP>python generate.py -p "A painting of an apple in a fruit bowl"
Traceback (most recent call last):
  File "C:\Users\Milaj\github\VQGAN-CLIP\generate.py", line 466, in <module>
    model = load_vqgan_model(args.vqgan_config, args.vqgan_checkpoint).to(device)
  File "C:\Users\Milaj\github\VQGAN-CLIP\generate.py", line 436, in load_vqgan_model
    config = OmegaConf.load(config_path)
  File "C:\Users\Milaj\anaconda3\envs\vqgan\lib\site-packages\omegaconf\omegaconf.py", line 183, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Milaj\\github\\VQGAN-CLIP\\checkpoints\\vqgan_imagenet_f16_16384.yaml'

Thank you in advance, tell me if you need more infos

**Comment by nerdyrodent** [comment]
The error says you're trying to use vqgan_imagenet_f16_16384.yaml, but you have no such file or directory: 'C:\Users\Milaj\github\VQGAN-CLIP\checkpoints\vqgan_imagenet_f16_16384.yaml'

**Comment by glouglou2marseille** [comment]
Hi again, thank you but I downloaded the vqgan_imagenet_f16_16384 file manually and now it is located in my checkpoint folder is that correctly done ? The vqgan_imagenet_f16_16384 is a folder and not a .yaml or .ckpt,  it contain sub-folders for model.yaml and last.ckpt,  is it necesssary to extract and/or rename them ? Thank you

**Comment by nerdyrodent** [comment]
Run these commands to create the directory and download the model files:
```
mkdir checkpoints

curl -L -o checkpoints/vqgan_imagenet_f16_16384.yaml -C - "https://heibox.uni-heidelberg.de/d/a7530b09fed84f80a887/files/?p=%2Fconfigs%2Fmodel.yaml&dl=1"
curl -L -o checkpoints/vqgan_imagenet_f16_16384.ckpt -C - "https://heibox.uni-heidelberg.de/d/a7530b09fed84f80a887/files/?p=%2Fckpts%2Flast.ckpt&dl=1"
```

**Comment by glouglou2marseille** [comment]
It helped, thank you !
