### ISSUE TITLE
Guided Diffusion Version?

### ISSUE THREAD

**Issue by rlallen-nps** [nerdyrodent/VQGAN-CLIP#43]
Excellent job converting to python from Colab.  Would you consider doing the same for her other guided diffusion notebook?
[RiversHaveWings Guided Diffusion](https://colab.research.google.com/drive/1V66mUeJbXrTuQITvJunvnWVn96FEbSI3)

**Comment by afiaka87** [comment]
If you don't wish to duplicate effort feel free to use this implementation https://github.com/afiaka87/clip-guided-diffusion; still a bit of a WIP but mostly finishing up.

**Comment by nerdyrodent** [comment]
Also a WIP ;) - https://github.com/nerdyrodent/CLIP-Guided-Diffusion
