### ISSUE TITLE
problems with video generation

### ISSUE THREAD

**Issue by Lazersharkzzz** [nerdyrodent/VQGAN-CLIP#45]
when I try running the example line `python generate.py -p "The inside of a sphere" -zvid -i 4500 -zse 20 -vl 10 -zsc 0.97 -opt Adagrad -lr 0.15 -se 4500` i receive an error that states
`  File "C:\Users\user\VQGAN-CLIP\generate.py", line 808, in <module>
    p = Popen(['ffmpeg',
  File "C:\Users\user\anaconda3\envs\vqgan\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\user\anaconda3\envs\vqgan\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

im not really sure where to go withh this error and I dont know if this is a problem on my side or something with the program

**Comment by SnortingPixels** [comment]
Try installing ffmpeg. 
If you are Runiing with Ananconda try 

` conda install -c conda-forge ffmpeg`
