### ISSUE TITLE
Simple zoom option zooms into corner?

### ISSUE THREAD

**Issue by robertalanbevan** [nerdyrodent/VQGAN-CLIP#46]
Excuse my tech illiteracy if this is obvious. I'm on Windows. I'm trying to combine a zoom with the "storyboard" mode, with multiple sequential text inputs. Currently I only know how do this with the simple built-in zoom option (as opposed to zoom.sh), but it zooms into the bottom-right corner by, apparently, displacing the entire image up and left 5 pixels per iteration. Is there a solution to this?

Most likely unimportant, but here's what I use:
`python generate.py -p "Roses|photo:-1 ^ Sunflowers ^ Daisies ^ Daffodils" -cpe 1500 -zvid -i 6000 -zse 10 -vl 20 -zsc 1.005 -opt Adagrad -lr 0.15 -se 6000 -s 250 250`

**Comment by nerdyrodent** [comment]
Thanks - can't say I tested with other sizes, and as i happens the size you picked does that! I'll call it a feature for now ;) For now, if you change the size to 256 256 it will centre zoom as expected.

**Comment by nerdyrodent** [comment]
The new version should now zoom into the centre with user specified sizes such as 250 250. Turns out certain image sizes aren't quite what they say they are (with 250 being converted into 240 for the perceptor). The zoom is now based on this size, rather than the user provided size.
