### ISSUE TITLE
Error on taming.models

### ISSUE THREAD

**Issue by rlallen-nps** [nerdyrodent/VQGAN-CLIP#49]
Please consider adding to your setup instructions:

Was receiving an error:
File "generate.py", line 18, in <module>
    from taming.models import cond_transformer, vqgan
ModuleNotFoundError: No module named 'taming'

Solution:
pip3 install taming-transformers

**Comment by nerdyrodent** [comment]
Alternate method for install as discussed in the video (pip) has now been added top the readme.
