### ISSUE TITLE
Improvement: Add cog files

### ISSUE THREAD

**Issue by microraptor** [nerdyrodent/VQGAN-CLIP#50]
https://github.com/replicate/cog makes it easy to build Docker containers for machine learning. A cog.yaml has to be configured and the interface code written, which looks pretty straightforward. The project could probably be also be added here: https://replicate.ai/explore
Anyone who has Docker installed could then run it on there system as easy as executing something like this:
```sh
docker run -d -p 5000:5000 r8.im/nerdyrodent/VQGAN-CLIP@sha256:fe8d040a80609ff5643815e28bc3c488faf8870d968f19e045c4d0e043ffae59
curl http://localhost:5000/predict -X POST -F p="A painting of an apple in a fruit bowl"
```

**Comment by nerdyrodent** [comment]
There is now a cog.yaml file
