### ISSUE TITLE
I keep getting a traceback trying to make a video

### ISSUE THREAD

**Issue by constantupgrade** [nerdyrodent/VQGAN-CLIP#51]
in line 988 "AttributeError: 'int' object has no attribute 'stdin'"

ffmpeg command failed - check your installation
  0%|                                                                                                                                                           | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Caleb\VQGAN-CLIP\generate.py", line 988, in <module>
    im.save(p.stdin, 'PNG')
AttributeError: 'int' object has no attribute 'stdin'

Maybe i'm trying to make a video wrong, but the issue persists even with the provided example of the telephone box.

**Comment by SnortingPixels** [comment]
install ffmpeg ?

**Comment by Sebocto** [comment]
I am having the same issue and I have made sure ffmpeg is installed

**Comment by Ouroboratika** [comment]
> @Ouroboratika >then added C:\Program Files\ffmpeg\bin to my PATH environment variable.
> 
> Sorry I'm super new to this. How do I update that PATH variable? I'm in Anaconda viewer and it won't let me update.

Oh sure thing. I'm sure there's a way to do it in PowerShell but I'd have to look up the syntax. The GUI-driven way I did it is (assuming you're on Windows 10): 

- Press Win + Pause/Break to bring up your system information
- Click `Advanced System Settings`.
- In the window that opens, go to the `Advanced` tab, and click `Environment Variables`.
- From there, there's two sets of vars, `User` and `System`. In the `System` section, find a var called `PATH` (Mine actually showed up as `Path` so I don't know if the capitalization matters) and double click it.
    - (You _probably_ have a `PATH` var already, but if not, you can just create a new one and name it `PATH`).
- Click `New` to add a new path to the, uhh, `PATH` variable.
- Finally, paste in your path to the FFMPEG bin/ directory and press enter.

Hope that helps!
