### ISSUE TITLE
custom filename and location for video is giving errors

### ISSUE THREAD

**Issue by huzaifa207** [nerdyrodent/VQGAN-CLIP#66]
**-o** flag is working properly in the case of image generation, but there is no specific information is available on how to create video with custom name. In case of providing a file name with any extension the script result in the following error

`ValueError: unknown file extension: .png'`

On windows we cannot use the **zoom.sh** script in conda prompt. So using the command

`python generate.py -p "An apple in a bowl" -zvid -i 2000 -vl 10 -o "output/test.mp4"`

**Comment by nerdyrodent** [comment]
Use png images to create videos.
