### ISSUE TITLE
No matching distribution found for torch==1.9.0+cu111

### ISSUE THREAD

**Issue by OfficialCRUGG** [nerdyrodent/VQGAN-CLIP#75]
Hey there!
I'm trying to run this on an M1 MacBook Pro.

I installed Anaconda and created and activated the environment like in the Readme. Then I tried to run the first pip command, but I get an error:
![image](https://user-images.githubusercontent.com/25248999/137588984-8cf1e71a-6643-47bc-bb46-d51969995148.png)

Any clue what's causing this and how to fix it?

**Comment by very-meanly** [comment]
I was able to get around this by just removing the `+cu111` part.

**Comment by OfficialCRUGG** [comment]
I think I tried that, but I only removed it from 1.9.0, did you also remove it from 0.10.0? @very-meanly

**Comment by very-meanly** [comment]
> I think I tried that, but I only removed it from 1.9.0, did you also remove it from 0.10.0? @very-meanly

Yes.

**Comment by nerdyrodent** [comment]
Information for installing Pytorch is available at https://pytorch.org/get-started/locally/
Note that only Nvidia CUDA has been tested.

**Comment by gselsidi** [comment]
I left all the specific versions out, and just ran
`conda install pytorch`

**Comment by gselsidi** [comment]
> hey, did you manage to get
> 
> > I think I tried that, but I only removed it from 1.9.0, did you also remove it from 0.10.0? @very-meanly
> 
> hey, did you manage to get it working? What is the performance like on a M1 Mac?

running the basic apple in a bowl and performance is brutal, as pytroch doesn't support the M1's built in GPU yet, it's been running for over 30m and nothing I expect it to be fairly useless running just on the cpu.
