### ISSUE TITLE
ModuleNotFoundError: No module named 'taming'

### ISSUE THREAD

**Issue by JasonHoku** [nerdyrodent/VQGAN-CLIP#77]
Hello I've followed all the steps in the installation docs and ended up with this error:

```
(vqgan) C:\Users\JasonHoku\VQGAN\VQGAN-CLIP>python generate.py -p "A painting of an apple in a fruit bowl"
Traceback (most recent call last):
  File "C:\Users\JasonHoku\VQGAN\VQGAN-CLIP\generate.py", line 18, in <module>
    from taming.models import cond_transformer, vqgan
ModuleNotFoundError: No module named 'taming'
```

I didn't see anything in the issues list with a relevant report so I figured I'd list it here.

OS Name 	Microsoft Windows 10 Pro
Version	       10.0.19043 Build 19043
Processor	AMD Ryzen 7 3700X 8-Core Processor, 3593 Mhz, 8 Core(s), 16 Logical Processor(s)

**Comment by monsieurpooh** [comment]
Unfortunately does NOT work when using pyinstaller. Even when using `--hidden-import=”taming-transformers”` the exe file at the end will say taming module is missing.

**Comment by FlashlightET** [comment]
still getting the error. requirement already satisfied taming-transformers yet no module named taming.
