### ISSUE TITLE
which CUDA version is required for pytorch here?

### ISSUE THREAD

**Issue by christiansievers** [nerdyrodent/VQGAN-CLIP#8]
I'm getting `UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:115.)`. I do have a GPU, but I'm using CUDA version 8 (it's a shared lab machine). 

Is the old CUDA version why I get the above error? Any way to fix this, apart from setting up a brand new system?

**Comment by nerdyrodent** [comment]
I'm using CUDA 11 as it's a requirement for the RTX 30x series:
```pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html```
Not actually tested any versions prior, but CUDA 10 should also be OK.

**Comment by christiansievers** [comment]
Right. Thanks. I guess it's time to set everything up from scratch again. 

Just to check, in your instructions you mention that CLIP and taming-transformers also need to be present. Is just git cloning them enough, or do they also need to be installed, following the instructions on their respective pages?

**Comment by nerdyrodent** [comment]
I have OpenAI CLIP and taming-transformers available like this:
```
git clone https://github.com/openai/CLIP
git clone https://github.com/CompVis/taming-transformers.git
```
CLIP re: the pytorch 1.7.1 requirement, and tt re: gumbel support.

**Comment by mazzo23** [comment]
@nerdyrodent nice, was looking for that answer about cuda10. have to try that before switching os. ...i dont even say it out loud ^^
