### ISSUE TITLE
Single quotes around URLs in Setup of README

### ISSUE THREAD

**Issue by Chudroy** [nerdyrodent/VQGAN-CLIP#86]
Hi! Thanks for this amazing guide! 

I wanted to let you know that I was getting errors with the commands that have URLs in them. I looked around, and it's because of the use of single quotes instead of double quotes.

https://stackoverflow.com/questions/6884669/curl-1-protocol-https-not-supported-or-disabled-in-libcurl

Also, in your tutorial video, you use double quotes. When I use double quotes, I don't get any errors.

Just a heads up, thanks again for all your work!

**Comment by nerdyrodent** [comment]
Thanks, I'll update the readme!
