### ISSUE TITLE
 allways errors in trying free vqgan+clip     Do i need colab pro 

### ISSUE THREAD

**Issue by Jude2222** [nerdyrodent/VQGAN-CLIP#87]

**Comment by Jude2222** [comment]
Free version google  vqgan+clip  wont work - does colab pro work to fix this ? - I might be doing something wrong

**Comment by microraptor** [comment]
Have you been using [Katherine Crowson's VQGAN+CLIP Google Colab notebook](https://colab.research.google.com/drive/1ZAus_gn2RhTZWzOWUpPERNC0Q8OhZRTZ)?

This repo is for a locally run implementation of VQGAN+CLIP, which is not meant to be executed on Colab. This is probably not the right place to ask for help with the notebook linked above.
