### ISSUE TITLE
Cannot reproduce results from README.md

### ISSUE THREAD

**Issue by wprazuch** [nerdyrodent/VQGAN-CLIP#90]
Hello,
First of all, thank you for an amazing repository - this is both very spectacular and well-written.
I am having a problem reproducing the results from the `README.md` file though. I was trying to reproduce the following input:

`python generate.py -p "A painting of an apple in a fruit bowl"`

However, at the output I am obtaining the following image:

![output](https://user-images.githubusercontent.com/47665612/142052324-d392732c-aa93-4d91-a008-2156ebb5ad69.png)

Does anyone have the same issue or can guide me on what could be the reason for such discrepancies?
Regards

**Comment by nerdyrodent** [comment]
The seed is one big factor, but then even with a seed and some determinism turned on you'll get differences.

**Comment by wprazuch** [comment]
@nerdyrodent Yes, I thought about that, however, I guess this case also has problems with preserving the global structure. I can imagine the photo to not be identical to the example in the `README.md`, but regardless how much I try, I cannot create an image, which has a nice, round apple-looking object, and a proper bowl.

Any idea what is the problem? 🤔

**Comment by nerdyrodent** [comment]
If you want a round apple and a proper bowl, one way is to use an init image. Outside of that, you'll be looking at prompt engineering and luck ;)

**Comment by wprazuch** [comment]
All good. Seems like my A100 SXM did not like the drivers I installed (on Ubuntu 20.04) and produced such weird-looking output. Updating the drivers significantly improved the quality of results (don't know why, and still did not reproduce the results though :P). 

Interesting note: for the A100 SXM, the PyTorch version specified in the requirements had inference problems - an average iteration lasted 20 seconds. Raising the PyTorch version significantly sped up the inference (~10 times faster). This may be related to the GPU - SXM requires some additional packages for the inference to run fast and higher PyTorch versions include it and this one does not.
