### ISSUE TITLE
Zoom.sh Windows 10 port

### ISSUE THREAD

**Issue by Muwusiz** [nerdyrodent/VQGAN-CLIP#91]
has anyone converted zoom.sh to a bat or py to run on windows?

**Comment by nerdyrodent** [comment]
There is also a simple zoom video creation option available. For example:
```python generate.py -p "The inside of a sphere" -zvid -i 4500 -zse 20 -vl 10 -zsc 0.97 -opt Adagrad -lr 0.15 -se 4500```
