### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)

### ISSUE THREAD

**Issue by HzxLsy** [nerdyrodent/VQGAN-CLIP#92]
![image](https://user-images.githubusercontent.com/91897058/142755040-43459c39-afa2-4d62-a6d4-f2d93779537e.png)

**Comment by nerdyrodent** [comment]
Looks like you're out of VRAM. Have you tried with a smaller image?
