### ISSUE TITLE
Having an issue with modules not being installed

### ISSUE THREAD

**Issue by abdullahalhamidi** [nerdyrodent/VQGAN-CLIP#93]
ModuleNotFoundError: No module named 'google.protobuf'

Solution to this is conda install protobuf

but I have another module that's not working ModuleNotFoundError: No module named 'deprecate'

tried:
conda install deprecate
pip install deprecate
restarted the process like 3 times and still same issue any ideas?

**Comment by nerdyrodent** [comment]
Make sure your Nvidia drivers are installed and that ``nvidia-smi`` runs ok, then try over with a fresh conda environment.
