### ISSUE TITLE
Video Length argument seems to do nothing

### ISSUE THREAD

**Issue by Triplicata1** [nerdyrodent/VQGAN-CLIP#94]
I've been messing with this program the past couple days. I've been able to get video outputs but when I use the video length argument my expectation is that it would take the frames generated and create a timelapse that long. For example if I have '-vl 30' it would create a 30 second timelapse. However it doesn't seem to do anything and instead will create a video length based approximately off of how many frames were created divided by the output fps.

**Comment by nerdyrodent** [comment]
The line is ```fps = np.clip(total_frames/length,min_fps,max_fps)```. Min is 10, max is 60.
As an example, if total_frames = 30 & video length is 1, you'll get a 1 second long, 30fps video

**Comment by MSFTserver** [comment]
> 

this only accounts when doing cpu and fps is set below 9 though i think it would be handy if when using the video length option we used the -t option with ffmpeg to set a hard time on the videos length, experimenting with 100k iterations was making videos way to long around 20 minutes
