### ISSUE TITLE
the code doesn't find my GPU

### ISSUE THREAD

**Issue by piotr1235** [nerdyrodent/VQGAN-CLIP#95]
![image](https://user-images.githubusercontent.com/80777539/144596683-8d8384f0-16ac-42d5-bc2b-a34d63271746.png)

![image](https://user-images.githubusercontent.com/80777539/144690251-b5f2983a-bef7-4227-a25e-29e772c0966f.png)

**Comment by zhanghongyong123456** [comment]
> 

It is possible that your CUDA installed driver does not match the host driver

**Comment by piotr1235** [comment]
I fixed it by deleting Cuda and downloading it again and updating windows
