### ISSUE TITLE
Can't install PyTorch 1.9.1 and CU111

### ISSUE THREAD

**Issue by mandyBrigwell** [nerdyrodent/VQGAN-CLIP#96]
I get the error:

"Could not find a version that satisfies the requirement torch==1.9.1+cu111 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0)"

Hunting about on PyTorch.org in torch_stable.html, I can't find such a version either. My Googling skills are coming up short: any idea what to do?

I've got it running, but no GPU, so iterations are taking 15 seconds.

**Comment by nerdyrodent** [comment]
As a first step, make sure your Nvidia drivers are installed. Full details at https://pytorch.org/get-started/locally/ 
See also - https://github.com/pytorch/pytorch
