### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by HylisWilk** [nerdyrodent/VQGAN-CLIP#99]
When trying to use some of the models on the colab notebook (like the WikiArt model for instance) I'm getting an import error.
Something about taming.modules.misc not existing.

Anyone getting this same error? I already uncommented the line that installs taming-transformers and it still didn't fix it.

**Comment by abdullahalhamidi** [comment]
Same issue here it runs and generates but it errors out when I try to go in to debug and change image size

**Comment by nerdyrodent** [comment]
As mentioned in the videos and code, there is some difference between the pip install and git clone versions of taming-transformers. I found one worked with some, while the other worked with others. Apparently one option is shown below, though I've not tested it:

https://github.com/nerdyrodent/VQGAN-CLIP/issues/106#issuecomment-1003419726
